name: Latest Blog Post Workflow

on:
  schedule:
    # æ¯å¤© UTC 0 ç‚¹è¿è¡Œ
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Pull in CSDN blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "CSDN-BLOG-POST-LIST"
          feed_list: "https://blog.csdn.net/Grape_yan/rss/list"
          max_post_count: 5
          commit_message: "ğŸ“š Updated latest CSDN blog posts"
